name: PR Build Check

on:
  pull_request:
    branches: [ master ]

jobs:
  build-check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        yarn install --frozen-lockfile || yarn install
        yarn check --integrity

    - name: Build
      run: yarn build 